### ISSUE TITLE
Migrate from TravisCI to GHA

### ISSUE THREAD

**Issue by dblock** [slack-ruby/slack-ruby-bot-server-events#12]
<img width="1427" alt="Screen Shot 2022-02-28 at 6 07 38 PM" src="https://user-images.githubusercontent.com/542335/156073683-3bdfe97e-df3e-409c-8a7d-0c5f03d9b41b.png">

**Comment by CrazyOptimist** [comment]
Let me get this done

**Comment by CrazyOptimist** [comment]
Test fails on my local, for the `master` branch.  

Steps to reproduce:

- Clone the repo
- Ruby version used: 2.7.2
- Create a new gemset `rvm gemset create slack-ruby`
- Install dependencies `bundle install`
- Configure MongoDB connection and set env `RACK_ENV=test, DATABASE_ADAPTER=mongoid`
- Run test `rake spec`

Output:

```
An error occurred while loading ./spec/slack-ruby-bot-server-events/api/endpoints/slack/actions_endpoint_spec.rb.
Failure/Error: require 'slack-ruby-bot-server'

NameError:
  uninitialized constant SlackRubyBotServer::Api::Presenters::TeamPresenter::Boolean
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters/team_presenter.rb:13:in `<module:TeamPresenter>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters/team_presenter.rb:4:in `<module:Presenters>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters/team_presenter.rb:3:in `<module:Api>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters/team_presenter.rb:2:in `<module:SlackRubyBotServer>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters/team_presenter.rb:1:in `<top (required)>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters.rb:7:in `require_relative'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters.rb:7:in `<top (required)>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api.rb:7:in `require_relative'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api.rb:7:in `<top (required)>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server.rb:13:in `require_relative'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server.rb:13:in `<top (required)>'
# ./lib/slack-ruby-bot-server-events.rb:3:in `require'
# ./lib/slack-ruby-bot-server-events.rb:3:in `<top (required)>'
# ./spec/spec_helper.rb:6:in `<top (required)>'
# ./spec/slack-ruby-bot-server-events/api/endpoints/slack/actions_endpoint_spec.rb:3:in `require'
# ./spec/slack-ruby-bot-server-events/api/endpoints/slack/actions_endpoint_spec.rb:3:in `<top (required)>'

An error occurred while loading ./spec/slack-ruby-bot-server-events/api/endpoints/slack/commands_endpoint_spec.rb.
Failure/Error: require 'slack-ruby-bot-server'

NameError:
  uninitialized constant SlackRubyBotServer::Api::Presenters::TeamPresenter::Boolean
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters/team_presenter.rb:13:in `<module:TeamPresenter>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters/team_presenter.rb:4:in `<module:Presenters>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters/team_presenter.rb:3:in `<module:Api>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters/team_presenter.rb:2:in `<module:SlackRubyBotServer>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters/team_presenter.rb:1:in `<top (required)>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters.rb:7:in `require_relative'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters.rb:7:in `<top (required)>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api.rb:7:in `require_relative'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api.rb:7:in `<top (required)>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server.rb:13:in `require_relative'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server.rb:13:in `<top (required)>'
# ./lib/slack-ruby-bot-server-events.rb:3:in `require'
# ./lib/slack-ruby-bot-server-events.rb:3:in `<top (required)>'
# ./spec/spec_helper.rb:6:in `<top (required)>'
# ./spec/slack-ruby-bot-server-events/api/endpoints/slack/commands_endpoint_spec.rb:3:in `require'
# ./spec/slack-ruby-bot-server-events/api/endpoints/slack/commands_endpoint_spec.rb:3:in `<top (required)>'

An error occurred while loading ./spec/slack-ruby-bot-server-events/api/endpoints/slack/events_endpoint_spec.rb.
Failure/Error: require 'slack-ruby-bot-server'

NameError:
  uninitialized constant SlackRubyBotServer::Api::Presenters::TeamPresenter::Boolean
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters/team_presenter.rb:13:in `<module:TeamPresenter>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters/team_presenter.rb:4:in `<module:Presenters>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters/team_presenter.rb:3:in `<module:Api>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters/team_presenter.rb:2:in `<module:SlackRubyBotServer>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters/team_presenter.rb:1:in `<top (required)>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters.rb:7:in `require_relative'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters.rb:7:in `<top (required)>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api.rb:7:in `require_relative'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api.rb:7:in `<top (required)>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server.rb:13:in `require_relative'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server.rb:13:in `<top (required)>'
# ./lib/slack-ruby-bot-server-events.rb:3:in `require'
# ./lib/slack-ruby-bot-server-events.rb:3:in `<top (required)>'
# ./spec/spec_helper.rb:6:in `<top (required)>'
# ./spec/slack-ruby-bot-server-events/api/endpoints/slack/events_endpoint_spec.rb:3:in `require'
# ./spec/slack-ruby-bot-server-events/api/endpoints/slack/events_endpoint_spec.rb:3:in `<top (required)>'

An error occurred while loading ./spec/slack-ruby-bot-server-events/config_spec.rb.
Failure/Error: require 'slack-ruby-bot-server'

NameError:
  uninitialized constant SlackRubyBotServer::Api::Presenters::TeamPresenter::Boolean
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters/team_presenter.rb:13:in `<module:TeamPresenter>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters/team_presenter.rb:4:in `<module:Presenters>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters/team_presenter.rb:3:in `<module:Api>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters/team_presenter.rb:2:in `<module:SlackRubyBotServer>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters/team_presenter.rb:1:in `<top (required)>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters.rb:7:in `require_relative'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters.rb:7:in `<top (required)>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api.rb:7:in `require_relative'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api.rb:7:in `<top (required)>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server.rb:13:in `require_relative'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server.rb:13:in `<top (required)>'
# ./lib/slack-ruby-bot-server-events.rb:3:in `require'
# ./lib/slack-ruby-bot-server-events.rb:3:in `<top (required)>'
# ./spec/spec_helper.rb:6:in `<top (required)>'
# ./spec/slack-ruby-bot-server-events/config_spec.rb:3:in `require'
# ./spec/slack-ruby-bot-server-events/config_spec.rb:3:in `<top (required)>'

An error occurred while loading ./spec/slack-ruby-bot-server-events/version_spec.rb.
Failure/Error: require 'slack-ruby-bot-server'

NameError:
  uninitialized constant SlackRubyBotServer::Api::Presenters::TeamPresenter::Boolean
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters/team_presenter.rb:13:in `<module:TeamPresenter>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters/team_presenter.rb:4:in `<module:Presenters>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters/team_presenter.rb:3:in `<module:Api>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters/team_presenter.rb:2:in `<module:SlackRubyBotServer>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters/team_presenter.rb:1:in `<top (required)>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters.rb:7:in `require_relative'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api/presenters.rb:7:in `<top (required)>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api.rb:7:in `require_relative'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server/api.rb:7:in `<top (required)>'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server.rb:13:in `require_relative'
# /home/netfan/.rvm/gems/ruby-2.7.2@slack-ruby/gems/slack-ruby-bot-server-1.2.0/lib/slack-ruby-bot-server.rb:13:in `<top (required)>'
# ./lib/slack-ruby-bot-server-events.rb:3:in `require'
# ./lib/slack-ruby-bot-server-events.rb:3:in `<top (required)>'
# ./spec/spec_helper.rb:6:in `<top (required)>'
# ./spec/slack-ruby-bot-server-events/version_spec.rb:3:in `require'
# ./spec/slack-ruby-bot-server-events/version_spec.rb:3:in `<top (required)>'
No examples found.

Finished in 0.00005 seconds (files took 1.34 seconds to load)
0 examples, 0 failures, 5 errors occurred outside of examples
```

Do you have any clue?
@dblock

**Comment by dblock** [comment]
This happens because `Boolean` is not a native type in Ruby. It used to be aliased in Grape, see https://github.com/ruby-grape/grape/issues/1551 or https://github.com/ruby-grape/grape/issues/1115. I think changing the code to `Grape::API::Boolean` or locking grape to an older version should work.

**Comment by dblock** [comment]
Put up a PR that replaces Travis with GHA and I'll try to fix whatever is broken on top of it?

**Comment by CrazyOptimist** [comment]
Roger sir

**Comment by dblock** [comment]
I migrated slack-ruby-bot-server to GHA in https://github.com/slack-ruby/slack-ruby-bot-server/pull/142 and https://github.com/slack-ruby/slack-ruby-bot-server/pull/144, so you can copy from there.

The boolean problem was fixed in https://github.com/slack-ruby/slack-ruby-bot-server/pull/140, I released a new version of the gem, so it should go away.

**Comment by CrazyOptimist** [comment]
Got you, let me try
Thanks

**Comment by CrazyOptimist** [comment]
Cool
All the tests are green
