### ISSUE TITLE
Ruby 3.3.6 error: unitialized constant Pagy::Cursor

### ISSUE THREAD

**Issue by johnhutch** [slack-ruby/slack-ruby-bot-server-events#25]
Starting a new rails app with ruby-3.3.6 and Rails 7.2.2, my Gemfile includes the following gems:

```
gem "slack-ruby-bot-server-events"
gem "otr-activerecord"
gem "pagy_cursor"
```

Spinning up the app generates the following error:

```
/Users/johnhutchinson/.gem/ruby/3.3.6/gems/slack-ruby-bot-server-2.1.1/lib/slack-ruby-bot-server/api/helpers/cursor_helpers.rb:28:in `<module:CursorHelpers>': uninitialized constant Pagy::Cursor (NameError)

          include Pagy::Cursor::Backend
                      ^^^^^^^^
	from /Users/johnhutchinson/.gem/ruby/3.3.6/gems/slack-ruby-bot-server-2.1.1/lib/slack-ruby-bot-server/api/helpers/cursor_helpers.rb:4:in `<module:Helpers>'
	from /Users/johnhutchinson/.gem/ruby/3.3.6/gems/slack-ruby-bot-server-2.1.1/lib/slack-ruby-bot-server/api/helpers/cursor_helpers.rb:3:in `<module:Api>'
	from /Users/johnhutchinson/.gem/ruby/3.3.6/gems/slack-ruby-bot-server-2.1.1/lib/slack-ruby-bot-server/api/helpers/cursor_helpers.rb:2:in `<module:SlackRubyBotServer>'
	from /Users/johnhutchinson/.gem/ruby/3.3.6/gems/slack-ruby-bot-server-2.1.1/lib/slack-ruby-bot-server/api/helpers/cursor_helpers.rb:1:in `<main>'
	from /Users/johnhutchinson/.gem/ruby/3.3.6/gems/slack-ruby-bot-server-2.1.1/lib/slack-ruby-bot-server/api/helpers.rb:1:in `require_relative'
	from /Users/johnhutchinson/.gem/ruby/3.3.6/gems/slack-ruby-bot-server-2.1.1/lib/slack-ruby-bot-server/api/helpers.rb:1:in `<main>'
	from /Users/johnhutchinson/.gem/ruby/3.3.6/gems/slack-ruby-bot-server-2.1.1/lib/slack-ruby-bot-server/api.rb:6:in `require_relative'
	from /Users/johnhutchinson/.gem/ruby/3.3.6/gems/slack-ruby-bot-server-2.1.1/lib/slack-ruby-bot-server/api.rb:6:in `<main>'
	from /Users/johnhutchinson/.gem/ruby/3.3.6/gems/slack-ruby-bot-server-2.1.1/lib/slack-ruby-bot-server.rb:13:in `require_relative'
	from /Users/johnhutchinson/.gem/ruby/3.3.6/gems/slack-ruby-bot-server-2.1.1/lib/slack-ruby-bot-server.rb:13:in `<main>'
	from /Users/johnhutchinson/.rubies/ruby-3.3.6/lib/ruby/3.3.0/bundled_gems.rb:69:in `require'
	from /Users/johnhutchinson/.rubies/ruby-3.3.6/lib/ruby/3.3.0/bundled_gems.rb:69:in `block (2 levels) in replace_require'
	from /Users/johnhutchinson/.gem/ruby/3.3.6/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/johnhutchinson/.gem/ruby/3.3.6/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
	from /Users/johnhutchinson/.gem/ruby/3.3.6/gems/slack-ruby-bot-server-events-0.3.2/lib/slack-ruby-bot-server-events.rb:3:in `<main>'
	from <internal:/Users/johnhutchinson/.rubies/ruby-3.3.6/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/johnhutchinson/.rubies/ruby-3.3.6/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/johnhutchinson/.rubies/ruby-3.3.6/lib/ruby/3.3.0/bundled_gems.rb:69:in `block (2 levels) in replace_require'
	from /Users/johnhutchinson/.gem/ruby/3.3.6/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
	from /Users/johnhutchinson/.rubies/ruby-3.3.6/lib/ruby/3.3.0/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /Users/johnhutchinson/.rubies/ruby-3.3.6/lib/ruby/3.3.0/bundler/runtime.rb:55:in `each'
	from /Users/johnhutchinson/.rubies/ruby-3.3.6/lib/ruby/3.3.0/bundler/runtime.rb:55:in `block in require'
	from /Users/johnhutchinson/.rubies/ruby-3.3.6/lib/ruby/3.3.0/bundler/runtime.rb:44:in `each'
	from /Users/johnhutchinson/.rubies/ruby-3.3.6/lib/ruby/3.3.0/bundler/runtime.rb:44:in `require'
	from /Users/johnhutchinson/.rubies/ruby-3.3.6/lib/ruby/3.3.0/bundler.rb:212:in `require'
	from /Users/johnhutchinson/Sites/slouch/config/application.rb:7:in `<main>'
	from /Users/johnhutchinson/.rubies/ruby-3.3.6/lib/ruby/3.3.0/bundled_gems.rb:69:in `require'
	from /Users/johnhutchinson/.rubies/ruby-3.3.6/lib/ruby/3.3.0/bundled_gems.rb:69:in `block (2 levels) in replace_require'
	from /Users/johnhutchinson/.gem/ruby/3.3.6/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/johnhutchinson/.gem/ruby/3.3.6/gems/railties-7.2.2/lib/rails/command/actions.rb:15:in `require_application!'
	from /Users/johnhutchinson/.gem/ruby/3.3.6/gems/railties-7.2.2/lib/rails/command/actions.rb:19:in `boot_application!'
	from /Users/johnhutchinson/.gem/ruby/3.3.6/gems/railties-7.2.2/lib/rails/commands/routes/routes_command.rb:25:in `perform'
	from /Users/johnhutchinson/.gem/ruby/3.3.6/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
	from /Users/johnhutchinson/.gem/ruby/3.3.6/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/johnhutchinson/.gem/ruby/3.3.6/gems/railties-7.2.2/lib/rails/command/base.rb:178:in `invoke_command'
	from /Users/johnhutchinson/.gem/ruby/3.3.6/gems/railties-7.2.2/lib/rails/commands/routes/routes_command.rb:18:in `invoke_command'
	from /Users/johnhutchinson/.gem/ruby/3.3.6/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
	from /Users/johnhutchinson/.gem/ruby/3.3.6/gems/railties-7.2.2/lib/rails/command/base.rb:73:in `perform'
	from /Users/johnhutchinson/.gem/ruby/3.3.6/gems/railties-7.2.2/lib/rails/command.rb:71:in `block in invoke'
	from /Users/johnhutchinson/.gem/ruby/3.3.6/gems/railties-7.2.2/lib/rails/command.rb:149:in `with_argv'
	from /Users/johnhutchinson/.gem/ruby/3.3.6/gems/railties-7.2.2/lib/rails/command.rb:69:in `invoke'
	from /Users/johnhutchinson/.gem/ruby/3.3.6/gems/railties-7.2.2/lib/rails/commands.rb:18:in `<main>'
	from /Users/johnhutchinson/.rubies/ruby-3.3.6/lib/ruby/3.3.0/bundled_gems.rb:69:in `require'
	from /Users/johnhutchinson/.rubies/ruby-3.3.6/lib/ruby/3.3.0/bundled_gems.rb:69:in `block (2 levels) in replace_require'
	from /Users/johnhutchinson/.gem/ruby/3.3.6/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from bin/rails:4:in `<main>'
```

I'm not sure if this is the _most_ correct fix, but getting things working in my local environment was as simple as adding `require pagy_cursor` to /lib/slack-ruby-bot-server.rb 

I can submit a PR if you'd like, or let me know if there's some missing config or something stupid I'm doing. 

Thanks for all your efforts on this gem!

**Comment by johnhutch** [comment]
Profuse apologies, it was only shortly after reporting this that I noticed my app was, for some reason, pulling an older version of the gem.

**Comment by ant0nm** [comment]
I'm on Rails 8.1.1 and Ruby 3.47 and currently getting the same error. How did you end up resolving it?
```
There was an error while trying to load the gem 'slack-ruby-bot-server-events'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant Pagy::Cursor

Backtrace for gem load error is:
/Users/anton_moiseev/.rbenv/versions/3.4.7/lib/ruby/gems/3.4.0/gems/slack-ruby-bot-server-2.2.0/lib/slack-ruby-bot-server/api/helpers/cursor_helpers.rb:28:in '<module:CursorHelpers>'
/Users/anton_moiseev/.rbenv/versions/3.4.7/lib/ruby/gems/3.4.0/gems/slack-ruby-bot-server-2.2.0/lib/slack-ruby-bot-server/api/helpers/cursor_helpers.rb:4:in '<module:Helpers>'
/Users/anton_moiseev/.rbenv/versions/3.4.7/lib/ruby/gems/3.4.0/gems/slack-ruby-bot-server-2.2.0/lib/slack-ruby-bot-server/api/helpers/cursor_helpers.rb:3:in '<module:Api>'
/Users/anton_moiseev/.rbenv/versions/3.4.7/lib/ruby/gems/3.4.0/gems/slack-ruby-bot-server-2.2.0/lib/slack-ruby-bot-server/api/helpers/cursor_helpers.rb:2:in '<module:SlackRubyBotServer>'
/Users/anton_moiseev/.rbenv/versions/3.4.7/lib/ruby/gems/3.4.0/gems/slack-ruby-bot-server-2.2.0/lib/slack-ruby-bot-server/api/helpers/cursor_helpers.rb:1:in '<main>'
```
